# Generated by Django 4.0.6 on 2022-07-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activnost_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
